import React from 'react';
import {useRouter} from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import axios from 'axios';
import {buildDetailRequest} from '../functions/buildRequest';
import {Container} from '@mui/material';

/**
 * Detailコンポーネント
 * @param {*} props
 * @return {Component}
 */
export default function Detail(props) {
  // console.log(props.shop[0]);
  const shopDetail = props.shop[0];
  const router = useRouter();

  return (

    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container maxWidth='md'>
          <p>詳細ページ</p>
          <button onClick={() => router.back() }>戻る</button>
          <div>
            <p>店名：{shopDetail.name}</p>
            <p>ジャンル：{shopDetail.genre.name}</p>
            <p>予算：{shopDetail.budget.average}</p>
            <p>住所：{shopDetail.address}</p>
            <p>アクセス：{shopDetail.access}</p>
            <p>営業時間：{shopDetail.open}</p>
            <p>定休日：{shopDetail.close}</p>
            <p>コース：{shopDetail.course}</p>
            <p>飲み放題：{shopDetail.free_drink}</p>
            <p>食べ放題：{shopDetail.free_food}</p>
            <p>個室：{shopDetail.private_room}</p>
            <p>カード決済：{shopDetail.card}</p>
            <p>禁煙席：{shopDetail.non_smoking}</p>
            <Image
              src={shopDetail.photo.pc.l}
              width={200}
              height={200}
              alt={shopDetail.name}
              priority={true}
            />
          </div>
        </Container>
      </main>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  try {
    const url = buildDetailRequest(context.query);

    const gourmet = await axios.get(url);
    const shop = gourmet.data.results.shop;

    return {
      props: {
        params: context.query,
        shop,
      },
    };
  } catch (error) {
    return {
      redirect: {
        permanent: false,
        destination: '/',
      },
    };
  }
};
