import React from 'react';
import {useRouter} from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import axios from 'axios';
import {buildDetailRequest} from '../functions/buildRequest';
import {Container} from '@mui/material';
import {toast} from 'react-hot-toast';
import {getIndex} from '../functions/getIndex';
import Header from '../components/common/header';

/**
 * Detailコンポーネント
 * @param {*} props
 * @return {Component}
 */
export default function Detail(props) {
  console.log(props.shop);
  const shopDetail = props.shop;
  const router = useRouter();

  const setFavorite = () => {
    const myStorage = localStorage;
    const gourmetObject = {
      id: shopDetail.id,
      name: shopDetail.name,
      access: shopDetail.access,
      address: shopDetail.address,
      photo: shopDetail.photo.pc.l,
    };
    if (myStorage.getItem('favorite-gourmet')) {
      // お気に入りリスト取得
      const gourmetList = JSON.parse(myStorage.getItem('favorite-gourmet'));

      // 店が登録されているか確認
      const found = getIndex(shopDetail.id, gourmetList, 'id');
      console.log(found);

      if (found == -1) { // 未登録の場合
        gourmetList.push(gourmetObject);
        toast.success('お気に入り登録しました');
      } else { // 登録済みの場合
        gourmetList.splice(found, 1);
        toast.error('お気に入り解除しました');
      }
      // localStorageに保存
      myStorage.setItem('favorite-gourmet', JSON.stringify(gourmetList));
    } else {
      console.log('オブジェクトなし');
      myStorage.setItem('favorite-gourmet', JSON.stringify([gourmetObject]));
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
      <main className={styles.main}>
        <Container maxWidth='md'>
          <button id='favBtn' onClick={setFavorite}>お気に入り</button>
          <button onClick={() => router.back() }>戻る</button>
          <div>
            <p>店名：{shopDetail.name}</p>
            <p>ジャンル：{shopDetail.genre.name}</p>
            <p>予算：{shopDetail.budget.average}</p>
            <p>住所：{shopDetail.address}</p>
            <p>アクセス：{shopDetail.access}</p>
            <p>営業時間：{shopDetail.open}</p>
            <p>定休日：{shopDetail.close}</p>
            <p>コース：{shopDetail.course}</p>
            <p>飲み放題：{shopDetail.free_drink}</p>
            <p>食べ放題：{shopDetail.free_food}</p>
            <p>個室：{shopDetail.private_room}</p>
            <p>カード決済：{shopDetail.card}</p>
            <p>禁煙席：{shopDetail.non_smoking}</p>
            <Image
              src={shopDetail.photo.pc.l}
              width={200}
              height={200}
              alt={shopDetail.name}
              priority={true}
            />
          </div>
        </Container>
      </main>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  try {
    const url = buildDetailRequest(context.query);

    const gourmet = await axios.get(url);
    const shop = gourmet.data.results.shop;

    return {
      props: {
        params: context.query,
        shop: shop[0],
      },
    };
  } catch (error) {
    console.log(error);
    return {
      redirect: {
        permanent: false,
        destination: '/',
      },
    };
  }
};
