import React, {useState, useEffect} from 'react';
import {useRouter} from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import {Container} from '@mui/material';
import ArrowBackIosIcon from '@mui/icons-material/ArrowBackIos';
import TrainIcon from '@mui/icons-material/Train';
import MapIcon from '@mui/icons-material/Map';
import CurrencyYenIcon from '@mui/icons-material/CurrencyYen';

import Header from '../components/common/header';

// import styles from '../styles/List.module.scss';
import styles from '../styles/Favorite.module.scss';

/**
 * Favoriteコンポーネント
 * @param {*} props
 * @return {Component}
 */
export default function Favorite() {
  const router = useRouter();

  const [favoriteList, setFavoriteList] = useState([]);

  useEffect(() => {
    const myStorage = localStorage;
    setFavoriteList(JSON.parse(myStorage.getItem('favorite-gourmet')));
  }, []);

  const detailPage = (shopId) => {
    const params = {
      id: shopId, // 店ID
      format: 'json', // レスポンス形式
    };
    router.push({
      pathname: '/detail',
      query: params,
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>お気に入りのお店</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
      <main className={styles.main}>
        <Container maxWidth='md'>
          <div className={styles.title_box}>
            <Link href='/'>
              <ArrowBackIosIcon fontSize='large' style={{color: '#333333'}}/>
            </Link>
            <h2>お気に入りのお店</h2>
          </div>

          <div className={styles.fav_card_container}>
            {favoriteList.map((val, i) => {
              return (
                <div
                  key={i}
                  className={styles.fav_card}
                  onClick={() => detailPage(val.id)}>
                  <Image
                    src={val.photo}
                    width={150}
                    height={150}
                    alt={val.name}
                    style={{border: '1px solid #CCCCCC'}}
                  />
                  <div className={styles.fav_card_inner}>
                    <p className={styles.genre}>{val.genre}</p>
                    <p className={styles.name}>{val.name}</p>
                    <div className={styles.access}>
                      <TrainIcon />
                      <p>{val.access}</p>
                    </div>
                    <div className={styles.address}>
                      <MapIcon />
                      <p>{val.address}</p>
                    </div>
                    <div className={styles.budget}>
                      <CurrencyYenIcon />
                      <p>{val.budget}</p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </Container>
      </main>
    </div>
  );
}
