import React, {useState, useEffect} from 'react';
import {useRouter} from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import {Container, Grid, Link} from '@mui/material';
import Header from '../components/common/header';

import styles from '../styles/List.module.scss';

/**
 * Favoriteコンポーネント
 * @param {*} props
 * @return {Component}
 */
export default function Favorite() {
  // console.log(props.shop);
  // const shopDetail = props.shop;
  const router = useRouter();

  const [favoriteList, setFavoriteList] = useState([]);

  useEffect(() => {
    const myStorage = localStorage;
    setFavoriteList(JSON.parse(myStorage.getItem('favorite-gourmet')));
  }, []);

  const detailPage = (shopId) => {
    const params = {
      id: shopId, // 店ID
      format: 'json', // レスポンス形式
    };
    router.push({
      pathname: '/detail',
      query: params,
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
      <main className={styles.main}>
        <Link href='/'>戻る</Link>
        <Container maxWidth='md'>
          <p>お気に入りのお店</p>
          <Grid container spacing={3} alignItems='center'>
            {favoriteList.map((val, i) => {
              return (
                <Grid item key={i} xs={12}>
                  <div
                    className={styles.shopCard}
                    onClick={() => detailPage(val.id)}>
                    <Image
                      src={val.photo}
                      width={150}
                      height={150}
                      alt={val.name}
                      style={{borderRadius: '5px'}}
                    />
                    <div className={styles.shopCard_inner}>
                      {/* <p>{val.genre.name}</p> */}
                      <p style={{fontSize: '1.4rem'}}>{val.name}</p>
                      <p>{val.access}</p>
                      <p>{val.address}</p>
                    </div>
                  </div>
                </Grid>
              );
            })}
          </Grid>
        </Container>
      </main>
    </div>
  );
}
