import React from 'react';
import {useRouter} from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import {buildListRequest} from '../functions/buildRequest';
import {Container, Grid, Link, Button} from '@mui/material';

import styles from '../styles/List.module.scss';

/**
 * Listコンポーネント
 * @param {*} props
 * @return {Component}
 */
export default function List(props) {
  const router = useRouter();
  const query = props.params;
  const gourmetList = props.shop;
  const paging = props.paging;

  // console.log(router.query);
  // console.log(props);

  const detailPage = (shopId) => {
    const params = {
      id: shopId, // 店ID
      format: 'json', // レスポンス形式
    };
    router.push({
      pathname: '/detail',
      query: params,
    });
  };

  const nextPage = () => {
    const params = {
      lat: query.lat, // 緯度
      lng: query.lng, // 経度
      range: query.range, // 半径
      genre: query.genre, // お店ジャンル
      start: parseInt(query.start) + parseInt(query.count), // 取得位置
      count: 10, // 最大取得数
      format: 'json', // レスポンス形式
    };
    router.push({
      pathname: '/list',
      query: params,
    });
  };
  const prevPage = () => {
    const params = {
      lat: query.lat, // 緯度
      lng: query.lng, // 経度
      range: query.range, // 半径
      genre: query.genre, // お店ジャンル
      start: parseInt(query.start) - parseInt(query.count), // 取得位置
      count: 10, // 最大取得数
      format: 'json', // レスポンス形式
    };
    router.push({
      pathname: '/list',
      query: params,
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>一覧ページ</p>
        <Link href='/'>戻る</Link>
        <Container maxWidth="md">

          <Button
            disabled={!paging.canPrev}
            variant="outlined"
            onClick={prevPage}>prev</Button>
          <span>{paging.available}件 {paging.start}〜{paging.end}件を表示</span>
          <Button
            disabled={!paging.canNext}
            variant="outlined"
            onClick={nextPage}>next</Button>

          <Grid container spacing={3} alignItems='center'>
            {gourmetList.map((val, i) => {
              return (
                <Grid item key={i} xs={12}>
                  <div
                    className={styles.shopCard}
                    onClick={() => detailPage(val.id)}>
                    <Image
                      src={val.photo.pc.l}
                      width={150}
                      height={150}
                      alt={val.name}
                      style={{borderRadius: '5px'}}
                    />
                    <div className={styles.shopCard_inner}>
                      <p>{val.genre.name}</p>
                      <p style={{fontSize: '1.4rem'}}>{val.name}</p>
                      <p>{val.access}</p>
                      <p>{val.address}</p>
                    </div>
                  </div>
                </Grid>
              );
            })}
          </Grid>

          <Button
            disabled={!paging.canPrev}
            variant="outlined"
            onClick={prevPage}>prev</Button>
          <Button
            disabled={!paging.canNext}
            variant="outlined"
            onClick={nextPage}>next</Button>
        </Container>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  try {
    const query = context.query;
    const url = buildListRequest(query);

    let canPrev = false;
    let canNext = false;

    const gourmet = await axios.get(url);
    const shop = gourmet.data.results.shop;
    const shopCount = gourmet.data.results.results_available;

    if ((parseInt(query.start) - parseInt(query.count)) > 0) {
      canPrev = true;
    }

    if ((parseInt(query.start) + parseInt(query.count) - 1) < shopCount) {
      canNext = true;
    }

    return {
      props: {
        params: context.query,
        shop,
        paging: {
          canPrev,
          canNext,
          available: shopCount,
          start: parseInt(query.start),
          end: parseInt(query.start) + shop.length - 1,
        },
      },
    };
  } catch (error) {
    return {
      redirect: {
        permanent: false,
        destination: '/',
      },
    };
  }
};
